"""Initial migration

Revision ID: 22abee762b62
Revises:
Create Date: 2026-03-19 00:32:56.451902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "22abee762b62"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("reviews", sa.Column("user_email", sa.String(), nullable=True))
    op.create_foreign_key(None, "reviews", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_column("reviews", "user_email")
    op.drop_column("reviews", "user_id")
    # ### end Alembic commands ###
